add dashboard widgets
Funfunz/backoffice pull request #18
Opened 2020-12-11 11:46 UTC by rubentlc

2020-12-11 11:52 UTC, joaogsleite approved these changes

2020-12-11 16:15 UTC, JWebCoder commented
Hello, in terms of the layout I have some points:

- we need a border on the bottom
- dismiss should dismiss and save that choice on local storage for now
- we need the at a glance working to have some page content

2020-12-11 16:35 UTC, JWebCoder requested changes

2020-12-11 16:35 UTC, JWebCoder commented on src/components/dashboard/components/at-a-glance/index.tsx
> +      let isToAddItem = entitiesFilter.length > 0
entitiesFilter.length && entitiesFilter.indexOf(table.name) is enough to make the check

2020-12-11 16:35 UTC, JWebCoder commented on src/components/dashboard/components/at-a-glance/index.tsx
> +    api.post('/?', {
move this to the services layer. Create a new entry called something like "getEntitiesCount" that receives an array of entities to retrieve the count

2020-12-11 16:35 UTC, JWebCoder commented on src/components/dashboard/components/at-a-glance/index.tsx
> +      body: JSON.stringify({
Check the services layer, we are using gql to help on building the queries

2020-12-11 16:35 UTC, JWebCoder commented on src/components/dashboard/components/at-a-glance/index.tsx
> +      setEntities(entities);
Use the recost state management instead of the useState, it gives you the possibility to show data to the user while making a new request in the background by leveraging the data already saved on recost

2020-12-11 16:35 UTC, JWebCoder commented on src/components/dashboard/components/more-actions/index.tsx
> +import Widget from './../widget';
you don't need to use relative import

2020-12-11 16:35 UTC, JWebCoder commented on src/components/dashboard/components/more-actions/style.module.scss
> +  a {
always use a class

2020-12-14 15:19 UTC, rubentlc commented
the changes are done. you can review the PR again

2020-12-17 10:40 UTC, JWebCoder approved these changes

2020-12-17 10:40 UTC, merged