Feature/FUNFUNZ-23 table pagination
Funfunz/backoffice pull request #9
Opened 2020-11-23 21:23 UTC by miriampereira

2020-11-23 22:29 UTC, joaogsleite commented on src/services/api/models/table.ts
> +        body: JSON.stringify({
Should we use a shared service for all graphql requests to prevent JSON.stringifies etc?

2020-11-23 22:59 UTC, JWebCoder requested changes

2020-11-23 22:59 UTC, JWebCoder commented on src/components/table/components/pagination/style.module.scss
> +        background-color: grey;
All colors should come from the theme

2020-11-23 22:59 UTC, JWebCoder commented on src/reducers/table.ts
> +export const FETCH_TABLE_CHANGE_ITEMS_BY_PAGE = 'FETCH_TABLE_CHANGE_ITEMS_BY_PAGE'
The name should be the actual action to prefrom, for example, SET_QUANTITY_ITEMS_BY_PAGE

2020-11-23 22:59 UTC, JWebCoder commented on src/services/api/models/table.ts
> +  getAllItemsNumber(table: ITable) {
Can we call this getEntityItemsCount ? Also, always set the return value of a function.

2020-11-23 22:59 UTC, JWebCoder commented on src/services/api/models/table.ts
> +          ${table.name}Count
Save this to a const and use it forward

2020-11-23 22:59 UTC, JWebCoder commented on src/services/api/models/table.ts
> +        return [];
This should be 0 right?

2020-11-23 22:59 UTC, JWebCoder commented on src/services/api/models/table.ts
> +          return data;
It should dispatch the result to the application context right?

2020-11-23 22:59 UTC, JWebCoder commented on src/components/table/components/pagination/index.tsx
> +  const updateTable = useCallback(
useCallback returns a memoized version of a function that returns always the same if the dependencies don't change.
Since you are creating updateTable on every rerender, the updateTable variable is always new.
Because of this all other useCallback's that use updateTable has a dependency will never actually memoize any result, so the use of useCallback is not required here.

2020-11-23 22:59 UTC, JWebCoder commented on src/components/table/components/pagination/index.tsx
> +    [page, updateTable]
This is an issue with memoize

2020-11-23 22:59 UTC, JWebCoder commented on src/components/table/components/pagination/index.tsx
> +    [itemsByPage, updateTable]
This is an issue with memoize

2020-11-23 22:59 UTC, JWebCoder commented on src/reducers/table.ts
> +  itemsByPage: 10,
Can we have this type of values in configuration file somewhere?
It would be good if we can have something like
```js
export const someConfig = {
  itemsPerPage: {
    default: 10,
    options: [ 10, 15, 20, 25, 30 ],
  },
}
```

2020-11-23 22:59 UTC, JWebCoder commented on src/services/api/models/table.ts
> +        body: JSON.stringify({
I think so, still the content of the JSON may be different per request basis, based on different filters/fields

What about [Apollo Client](https://www.apollographql.com/docs/react/)?

2020-11-24 17:20 UTC, JWebCoder requested changes

2020-11-24 17:20 UTC, JWebCoder commented on src/components/table/components/pagination/index.tsx
> +      updateTable(itemsByPage, p);
don't use single character variables

2020-12-01 00:35 UTC, JWebCoder approved these changes

2020-12-01 00:36 UTC, JWebCoder commented
@beajsilva , is this still a work in progress?

2020-12-01 00:43 UTC, merged